# Test $d

name: Test

on:
  push:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - name: Prerequisites
      run: sudo apt install libboost-all-dev libeigen3-dev

    - name: Download NextPnr
      run:  wget https://github.com/YosysHQ/nextpnr/archive/refs/heads/master.zip

    - name: Unzip
      run: unzip master.zip

    - name: Compile NextPnr
      run: |
        cd nextpnr-master/
        cmake . -DARCH=gowin -DGOWIN_BBA_EXECUTABLE=path
        make
