# Test $d

name: Test

on:
  push:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - name: Ubuntu update
      run:  sudo apt update

    - name: Verilog
      run:  sudo apt -y install iverilog

    - name: Yosys
      run:  wget -q https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2023-06-14/oss-cad-suite-linux-x64-20230614.tgz

    - name: Yosys unzip
      run: gunzip  oss-cad-suite-linux-x64-20230614.tgz

    - name: Yosys untar
      run: tar -xf oss-cad-suite-linux-x64-20230614.tar

    - name: Prerequisites
      run: sudo apt install libboost-all-dev libeigen3-dev

    - name: Download NextPnr
      run:  wget https://github.com/YosysHQ/nextpnr/archive/refs/heads/master.zip

    - name: Unzip
      run: unzip master.zip

    - name: Compile NextPnr
      run: |
        cd nextpnr-master/
        cmake . -DARCH=gowin -DGOWIN_BBA_EXECUTABLE=.local/bin/gowin_bba
        make
